### ISSUE TITLE
crypto_rs README.md

### ISSUE THREAD

**Issue by mateolafalce** [CM-IV/crypto-rs#1]
Hello!, 
I have recently used this encryptor and I find it great. I come to propose something for the `readme.md`. I see that you show the program with a screen shot of the screen, do you think it's a good idea to make a demonstration of it via .gif, for a more dynamic experience? 
I am willing to contribute of course!

**Comment by CM-IV** [comment]
Hey there @mateolafalce,

I'm glad to hear that you like `crypto_rs`, as I enjoyed using `fltk-rs` in its implementation.

I added a screenshot in the `README.md` for each branch of the repo, as the different branches have different ways of integrating the age encryption library.  I'm certainly open to the idea of gifs being used to show a demonstration.

I should probably also re-write the `README.md`s on each branch with more information.

**Comment by mateolafalce** [comment]
@CM-IV 
I'm glad to hear this. If you consider this proposal suitable for the project, I would be delighted to work with you on this. If you think that the project is fine as is, close the issue. 
I hear you!

**Comment by CM-IV** [comment]
I'll close this issue, but eventually I'd like to re-write the `README` files.  I won't get to that right now, I'm working on an `fltk-rs` app with an `sqlx` `sqlite` backend using the `fltk-evented` crate.
